"""Add paid field to sessions

Revision ID: da8c08fc368e
Revises: 94bcfb0a2fce
Create Date: 2019-06-11 05:40:49.162911

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da8c08fc368e'
down_revision = '94bcfb0a2fce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('paid', sa.Boolean(), nullable=True,
            default=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.drop_column('paid')

    # ### end Alembic commands ###
